// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package CodeRunner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CodeRunnerClient is the client API for CodeRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeRunnerClient interface {
	Judge(ctx context.Context, in *CodeRunnerRequest, opts ...grpc.CallOption) (*CodeRunnerRespone, error)
}

type codeRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeRunnerClient(cc grpc.ClientConnInterface) CodeRunnerClient {
	return &codeRunnerClient{cc}
}

func (c *codeRunnerClient) Judge(ctx context.Context, in *CodeRunnerRequest, opts ...grpc.CallOption) (*CodeRunnerRespone, error) {
	out := new(CodeRunnerRespone)
	err := c.cc.Invoke(ctx, "/CodeRunner.codeRunner/judge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeRunnerServer is the server API for CodeRunner service.
// All implementations must embed UnimplementedCodeRunnerServer
// for forward compatibility
type CodeRunnerServer interface {
	Judge(context.Context, *CodeRunnerRequest) (*CodeRunnerRespone, error)
	mustEmbedUnimplementedCodeRunnerServer()
}

// UnimplementedCodeRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedCodeRunnerServer struct {
}

func (UnimplementedCodeRunnerServer) Judge(context.Context, *CodeRunnerRequest) (*CodeRunnerRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Judge not implemented")
}
func (UnimplementedCodeRunnerServer) mustEmbedUnimplementedCodeRunnerServer() {}

// UnsafeCodeRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeRunnerServer will
// result in compilation errors.
type UnsafeCodeRunnerServer interface {
	mustEmbedUnimplementedCodeRunnerServer()
}

func RegisterCodeRunnerServer(s grpc.ServiceRegistrar, srv CodeRunnerServer) {
	s.RegisterService(&CodeRunner_ServiceDesc, srv)
}

func _CodeRunner_Judge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeRunnerServer).Judge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CodeRunner.codeRunner/judge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeRunnerServer).Judge(ctx, req.(*CodeRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeRunner_ServiceDesc is the grpc.ServiceDesc for CodeRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CodeRunner.codeRunner",
	HandlerType: (*CodeRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "judge",
			Handler:    _CodeRunner_Judge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/codeRunner/codeRunner.proto",
}
